### ISSUE TITLE
无法打开程序

### ISSUE THREAD

**Issue by mogmoug** [love2d-thirdparty/love2d-collects#1]
![image](https://user-images.githubusercontent.com/88359334/197760787-ff5b60ca-dd1c-4675-969e-844c457fc849.png)
![image](https://user-images.githubusercontent.com/88359334/197760967-38725252-f2db-4dc0-9b95-6ff7213f065d.png)

**Comment by 2439905184** [comment]
显卡太老了,我的集成显卡支持opengles 3.0 你的支持吗?

**Comment by 2439905184** [comment]
编辑器是他们用Godot引擎写的, 而且没开源. 可能用了GLES3.0 导致不兼容老设备

**Comment by mogmoug** [comment]
应该是吧
